spring.application.name=guestApp

spring.datasource.url=jdbc:mysql://localhost:3306/quest-app
spring.datasource.username=root
spring.datasource.password=trabzon61

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

questapp.app.secret=MzU2QWZiODN5a2FzazEyMzQ1Njc4OTAxMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
questapp.expires.in=604800

